// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DopamineNone/gedis/internal/app"
	"github.com/DopamineNone/gedis/conf"
	"github.com/DopamineNone/gedis/internal/tcp"
)

// Injectors from wire.go:

func wireApp() *app.App {
	handler := tcp.NewHandler()
	config := conf.New()
	listener := tcp.MustListener(config)
	appApp := app.New(handler, listener)
	return appApp
}
